import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,stat,readFile,chmod} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {NuanoxClient} from '../../examples/nuanox-client.mjs';import {setup} from './helpers.mjs';
async function withClient(fn){const dir=await mkdtemp(join(tmpdir(),'nuanox-client-test-'));try{const s=setup();const transport=(url,init)=>s.handle(new Request(url,init));const c=await NuanoxClient.initialize('http://localhost',join(dir,'credential.json'),transport);await fn(c,s,dir,transport);}finally{await rm(dir,{recursive:true,force:true});}}
test('external client persists credential before enrollment and safely replays after reload',()=>withClient(async(c,s,dir,transport)=>{assert.equal((await stat(c.path)).mode&0o077,0);assert.equal(s.calls.length,0);const one=await c.enroll('SYNTHETIC client');const loaded=await NuanoxClient.initialize(c.origin,c.path,transport);const two=await loaded.enroll('SYNTHETIC client');assert.equal(one.data.agent.id,two.data.agent.id);assert.equal(two.meta.replayed,true);assert.ok(!JSON.stringify(two).includes(c.credential));const me=(await loaded.request('/agents/self',{authenticate:true})).data;assert.equal(me.agent.id,one.data.agent.id);}));
test('client accepts documented short and full v2 paths',()=>withClient(async(c)=>{assert.equal((await c.request('/health')).data.status,'ok');assert.equal((await c.request('/api/v2/health')).data.status,'ok');}));
test('client request path cannot escape API/origin with token',()=>withClient(async(c,s)=>{for(const p of ['https://other.test/api/v2/x','//other.test/x','/../auth','/%2e%2e/auth','/api/v2/../auth','/api/v1/records','/records#x','/records\\x'])await assert.rejects(c.request(p,{authenticate:true}));assert.equal(s.calls.length,0);}));
test('client credential is bound to origin; no insecure remote HTTP',()=>withClient(async(c)=>{await assert.rejects(NuanoxClient.initialize('https://different.test',c.path));await assert.rejects(NuanoxClient.initialize('http://remote.test',c.path));}));
test('client refuses permissive local credential files',()=>withClient(async(c)=>{await chmod(c.path,0o644);await assert.rejects(NuanoxClient.initialize(c.origin,c.path));}));
test('client intent keys survive restart, canonical key order and response loss',()=>withClient(async(c,s,dir,transport)=>{const first=await c.intent('same',{a:1,b:2});assert.equal(await c.intent('same',{b:2,a:1}),first);const loaded=await NuanoxClient.initialize(c.origin,c.path,transport);assert.equal(await loaded.intent('same',{a:1,b:2}),first);await assert.rejects(c.intent('same',{a:2}));assert.notEqual(await c.intent('new',{a:2}),first);}));
test('distributed public client is byte-identical to tested client',async()=>{assert.deepEqual(await readFile(new URL('../../examples/nuanox-client.mjs',import.meta.url)),await readFile(new URL('../../public/agent/nuanox-client.mjs',import.meta.url)));});
