-- Stage 02 indexes, additional cross-row guards, and private-table RLS.
BEGIN;
CREATE FUNCTION knowledge.review_history_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ DECLARE p knowledge.reviews%ROWTYPE;BEGIN
 IF NEW.previous_review_id IS NOT NULL THEN
  SELECT * INTO p FROM knowledge.reviews WHERE id=NEW.previous_review_id;
  IF p.id IS NULL OR p.created_by<>NEW.created_by OR p.focus<>NEW.focus OR knowledge.row_ref(pg_catalog.to_jsonb(p),'target')<>knowledge.row_ref(pg_catalog.to_jsonb(NEW),'target') THEN RAISE EXCEPTION 'KB:REVIEW_HEAD_CHANGED';END IF;
 END IF;RETURN NEW;
END $$;
CREATE TRIGGER review_history_guard BEFORE INSERT ON knowledge.reviews FOR EACH ROW EXECUTE FUNCTION knowledge.review_history_guard();
CREATE FUNCTION knowledge.record_update_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'KB:FORBIDDEN'; END IF;
 IF (pg_catalog.to_jsonb(NEW)-ARRAY['version_counter','visibility'])<>(pg_catalog.to_jsonb(OLD)-ARRAY['version_counter','visibility']) THEN RAISE EXCEPTION 'KB:FORBIDDEN';END IF;
 IF NEW.visibility<>OLD.visibility AND pg_catalog.current_setting('knowledge.moderation',true) IS DISTINCT FROM 'on' THEN RAISE EXCEPTION 'KB:FORBIDDEN';END IF;
 IF NEW.version_counter<>OLD.version_counter AND NEW.version_counter<>OLD.version_counter+1 THEN RAISE EXCEPTION 'KB:VALIDATION_FAILED';END IF;RETURN NEW;
END $$;
CREATE TRIGGER record_update_guard BEFORE UPDATE OR DELETE ON knowledge.records FOR EACH ROW EXECUTE FUNCTION knowledge.record_update_guard();
CREATE FUNCTION knowledge.work_update_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'KB:FORBIDDEN';END IF;
 IF (pg_catalog.to_jsonb(NEW)-ARRAY['status','revision','assigned_to','updated_at','resolution_event_id','visibility'])<>(pg_catalog.to_jsonb(OLD)-ARRAY['status','revision','assigned_to','updated_at','resolution_event_id','visibility']) THEN RAISE EXCEPTION 'KB:FORBIDDEN';END IF;
 IF NEW.visibility<>OLD.visibility THEN
  IF pg_catalog.current_setting('knowledge.moderation',true) IS DISTINCT FROM 'on' OR (pg_catalog.to_jsonb(NEW)-'visibility')<>(pg_catalog.to_jsonb(OLD)-'visibility') THEN RAISE EXCEPTION 'KB:FORBIDDEN';END IF;
 ELSE IF NEW.revision<>OLD.revision+1 THEN RAISE EXCEPTION 'KB:TASK_REVISION_CONFLICT';END IF;END IF;RETURN NEW;
END $$;
CREATE TRIGGER work_update_guard BEFORE UPDATE OR DELETE ON knowledge.work_requests FOR EACH ROW EXECUTE FUNCTION knowledge.work_update_guard();
CREATE FUNCTION knowledge.work_event_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ DECLARE w knowledge.work_requests%ROWTYPE;e knowledge.work_events%ROWTYPE;BEGIN
 SELECT * INTO w FROM knowledge.work_requests WHERE id=NEW.id;
 SELECT * INTO e FROM knowledge.work_events WHERE work_request_id=w.id AND revision=w.revision;
 IF e.id IS NULL OR e.state_after<>w.status OR e.assigned_after IS DISTINCT FROM w.assigned_to OR e.resolution_event_after IS DISTINCT FROM w.resolution_event_id THEN RAISE EXCEPTION 'KB:VALIDATION_FAILED';END IF;RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER work_event_guard AFTER INSERT OR UPDATE ON knowledge.work_requests DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION knowledge.work_event_guard();

CREATE FUNCTION knowledge.work_resolution_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ DECLARE expected jsonb;ref jsonb;ev knowledge.work_events%ROWTYPE;BEGIN
 SELECT coalesce(pg_catalog.jsonb_agg(knowledge.row_ref(pg_catalog.to_jsonb(l),'target') ORDER BY ordinal),'[]'::jsonb) INTO expected FROM knowledge.work_resolution_links l WHERE event_id=NEW.id;
 IF expected<>NEW.resolution_refs OR (NEW.action='resolve' AND pg_catalog.jsonb_array_length(expected)=0) OR (NEW.action<>'resolve' AND expected<>'[]'::jsonb) THEN RAISE EXCEPTION 'KB:VALIDATION_FAILED';END IF;
 IF NEW.resolution_event_after IS NOT NULL THEN
  SELECT * INTO ev FROM knowledge.work_events WHERE id=NEW.resolution_event_after;
  IF ev.work_request_id<>NEW.work_request_id OR ev.action<>'resolve' THEN RAISE EXCEPTION 'KB:VALIDATION_FAILED';END IF;
 END IF;RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER work_resolution_guard AFTER INSERT ON knowledge.work_events DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION knowledge.work_resolution_guard();
CREATE FUNCTION knowledge.review_head_identity_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN
 IF TG_OP='DELETE' OR ROW(NEW.actor_id,NEW.target_kind,NEW.target_id,NEW.focus) IS DISTINCT FROM ROW(OLD.actor_id,OLD.target_kind,OLD.target_id,OLD.focus) THEN RAISE EXCEPTION 'KB:FORBIDDEN';END IF;RETURN NEW;
END $$;
CREATE TRIGGER review_head_identity_guard BEFORE UPDATE OR DELETE ON knowledge.review_heads FOR EACH ROW EXECUTE FUNCTION knowledge.review_head_identity_guard();
CREATE INDEX versions_history ON knowledge.versions(record_id,version_no DESC);
CREATE INDEX anchors_range ON knowledge.anchors(version_id,start_cp,end_cp);
CREATE INDEX sources_order ON knowledge.sources(created_at DESC,id);
CREATE INDEX records_order ON knowledge.records(created_at DESC,id);
CREATE INDEX work_status_order ON knowledge.work_requests(status,created_at DESC,id);
CREATE INDEX jobs_claim ON knowledge.embedding_jobs(state,next_attempt_at,id);
CREATE INDEX snapshots_expiry ON knowledge.query_snapshots(expires_at);
CREATE UNIQUE INDEX unit_logical_identity ON knowledge.search_units(
 unit_kind,coalesce(version_id,object_version_id,object_anchor_id,object_source_id,object_relation_id,object_annotation_id,object_evidence_id,object_review_id),coalesce(start_cp,-1),coalesce(end_cp,-1),coalesce(json_pointer,''),ordinal,chunker_version);
ALTER TABLE knowledge.schema_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge.actors ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_agents_actor_id ON knowledge.agents(actor_id);
CREATE INDEX fk_agents_owner_actor_id ON knowledge.agents(owner_actor_id);
ALTER TABLE knowledge.agents ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_agent_keys_actor_id ON knowledge.agent_keys(actor_id);
ALTER TABLE knowledge.agent_keys ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_operators_actor_id ON knowledge.operators(actor_id);
ALTER TABLE knowledge.operators ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_records_created_by ON knowledge.records(created_by);
ALTER TABLE knowledge.records ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_versions_created_by ON knowledge.versions(created_by);
CREATE INDEX fk_versions_record_id ON knowledge.versions(record_id);
CREATE INDEX fk_versions_parent_version_id ON knowledge.versions(parent_version_id);
ALTER TABLE knowledge.versions ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_version_changes_version_id ON knowledge.version_changes(version_id);
ALTER TABLE knowledge.version_changes ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_anchors_created_by ON knowledge.anchors(created_by);
CREATE INDEX fk_anchors_version_id ON knowledge.anchors(version_id);
ALTER TABLE knowledge.anchors ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_sources_created_by ON knowledge.sources(created_by);
ALTER TABLE knowledge.sources ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_relations_created_by ON knowledge.relations(created_by);
CREATE INDEX fk_relations_from_version_id ON knowledge.relations(from_version_id);
CREATE INDEX fk_relations_from_anchor_id ON knowledge.relations(from_anchor_id);
CREATE INDEX fk_relations_from_source_id ON knowledge.relations(from_source_id);
CREATE INDEX fk_relations_to_version_id ON knowledge.relations(to_version_id);
CREATE INDEX fk_relations_to_anchor_id ON knowledge.relations(to_anchor_id);
CREATE INDEX fk_relations_to_source_id ON knowledge.relations(to_source_id);
ALTER TABLE knowledge.relations ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_annotations_created_by ON knowledge.annotations(created_by);
CREATE INDEX fk_annotations_anchor_id ON knowledge.annotations(anchor_id);
CREATE INDEX fk_annotations_concept_version_id ON knowledge.annotations(concept_version_id);
CREATE INDEX fk_annotations_supersedes_annotation_id ON knowledge.annotations(supersedes_annotation_id);
ALTER TABLE knowledge.annotations ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_evidence_created_by ON knowledge.evidence(created_by);
CREATE INDEX fk_evidence_target_version_id ON knowledge.evidence(target_version_id);
CREATE INDEX fk_evidence_target_anchor_id ON knowledge.evidence(target_anchor_id);
CREATE INDEX fk_evidence_target_source_id ON knowledge.evidence(target_source_id);
CREATE INDEX fk_evidence_target_relation_id ON knowledge.evidence(target_relation_id);
CREATE INDEX fk_evidence_target_annotation_id ON knowledge.evidence(target_annotation_id);
CREATE INDEX fk_evidence_source_id ON knowledge.evidence(source_id);
CREATE INDEX fk_evidence_source_version_id ON knowledge.evidence(source_version_id);
CREATE INDEX fk_evidence_source_anchor_id ON knowledge.evidence(source_anchor_id);
ALTER TABLE knowledge.evidence ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_reviews_created_by ON knowledge.reviews(created_by);
CREATE INDEX fk_reviews_target_version_id ON knowledge.reviews(target_version_id);
CREATE INDEX fk_reviews_target_anchor_id ON knowledge.reviews(target_anchor_id);
CREATE INDEX fk_reviews_target_source_id ON knowledge.reviews(target_source_id);
CREATE INDEX fk_reviews_target_relation_id ON knowledge.reviews(target_relation_id);
CREATE INDEX fk_reviews_target_annotation_id ON knowledge.reviews(target_annotation_id);
CREATE INDEX fk_reviews_target_evidence_id ON knowledge.reviews(target_evidence_id);
CREATE INDEX fk_reviews_previous_review_id ON knowledge.reviews(previous_review_id);
ALTER TABLE knowledge.reviews ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_review_heads_actor_id ON knowledge.review_heads(actor_id);
CREATE INDEX fk_review_heads_review_id ON knowledge.review_heads(review_id);
ALTER TABLE knowledge.review_heads ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_work_requests_created_by ON knowledge.work_requests(created_by);
CREATE INDEX fk_work_requests_target_version_id ON knowledge.work_requests(target_version_id);
CREATE INDEX fk_work_requests_target_anchor_id ON knowledge.work_requests(target_anchor_id);
CREATE INDEX fk_work_requests_target_source_id ON knowledge.work_requests(target_source_id);
CREATE INDEX fk_work_requests_assigned_to ON knowledge.work_requests(assigned_to);
ALTER TABLE knowledge.work_requests ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_work_events_work_request_id ON knowledge.work_events(work_request_id);
CREATE INDEX fk_work_events_actor_id ON knowledge.work_events(actor_id);
CREATE INDEX fk_work_events_assigned_after ON knowledge.work_events(assigned_after);
CREATE INDEX fk_work_events_resolution_event_after ON knowledge.work_events(resolution_event_after);
ALTER TABLE knowledge.work_events ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_work_resolution_links_event_id ON knowledge.work_resolution_links(event_id);
CREATE INDEX fk_work_resolution_links_target_version_id ON knowledge.work_resolution_links(target_version_id);
CREATE INDEX fk_work_resolution_links_target_anchor_id ON knowledge.work_resolution_links(target_anchor_id);
CREATE INDEX fk_work_resolution_links_target_source_id ON knowledge.work_resolution_links(target_source_id);
ALTER TABLE knowledge.work_resolution_links ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_mutation_receipts_actor_id ON knowledge.mutation_receipts(actor_id);
ALTER TABLE knowledge.mutation_receipts ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_audit_events_actor_id ON knowledge.audit_events(actor_id);
ALTER TABLE knowledge.audit_events ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_moderation_events_actor_id ON knowledge.moderation_events(actor_id);
ALTER TABLE knowledge.moderation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge.embedding_profiles ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_search_units_record_id ON knowledge.search_units(record_id);
CREATE INDEX fk_search_units_version_id ON knowledge.search_units(version_id);
CREATE INDEX fk_search_units_object_version_id ON knowledge.search_units(object_version_id);
CREATE INDEX fk_search_units_object_anchor_id ON knowledge.search_units(object_anchor_id);
CREATE INDEX fk_search_units_object_source_id ON knowledge.search_units(object_source_id);
CREATE INDEX fk_search_units_object_relation_id ON knowledge.search_units(object_relation_id);
CREATE INDEX fk_search_units_object_annotation_id ON knowledge.search_units(object_annotation_id);
CREATE INDEX fk_search_units_object_evidence_id ON knowledge.search_units(object_evidence_id);
CREATE INDEX fk_search_units_object_review_id ON knowledge.search_units(object_review_id);
ALTER TABLE knowledge.search_units ENABLE ROW LEVEL SECURITY;
CREATE INDEX fk_embedding_jobs_unit_id ON knowledge.embedding_jobs(unit_id);
ALTER TABLE knowledge.embedding_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge.query_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON SCHEMA knowledge FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON ALL TABLES IN SCHEMA knowledge FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA knowledge FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA knowledge FROM PUBLIC,anon,authenticated,service_role;
COMMIT;
